version: '3.5'

services:

  grafana:
    image: flaviostutz/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/data
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mypass

volumes:
  grafana:

