version: '3.5'

services:

  grafana:
    build: .
    image: flaviostutz/grafana:5.2.4
    ports:
      - 3000:3000
    volumes:
      - grafana:/data
    environment:
      - GF_LOG_LEVEL=debug

volumes:
  grafana:
